


#include "EDC.h"


void ADC1_init(){
	SETBIT(ADMUX,REFS0);//TO SELECT THE VCC VOLTAG
	CLRBIT(ADMUX,MUX0);
	SETBIT(ADCSRA,ADEN);//TO ENABLE THE ADC 
	SETBIT(ADCSRA,ADPS0);//TO SET PRESCALER 128 ,ADPS0 1 &2 MUST BE ONE
	SETBIT(ADCSRA,ADPS1);//TO SET PRESCALER 128 ,ADPS0 1 &2 MUST BE ONE
	SETBIT(ADCSRA,ADPS2);//TO SET PRESCALER 128 ,ADPS0 1 &2 MUST BE ONE
	
}

uint16_t ADC0_read(){
	SETBIT(ADCSRA,ADSC);//TO TAKE A SAMPLE
	while(READBIT(ADCSRA,ADSC)){}//TO STAY HERE UNTIL TAKING THE SAMPLE 
	return (ADCL+(ADCH <<8));
	
}
uint16_t ADC1_read(){
	SETBIT(ADCSRA,ADSC);//TO TAKE A SAMPLE
while(READBIT(ADCSRA,ADSC)){}//TO STAY HERE UNTIL TAKING THE SAMPLE
return (ADCL+(ADCH <<8));

}